### ISSUE TITLE
Idea: add a helper for logging

### ISSUE THREAD

**Issue by dcu** [apex/go-apex#16]
like a preconfigured logger to stderr or something that you can use to log from your function.

**Comment by tj** [comment]
Logging is pretty subjective unfortunately. I use https://github.com/apex/log but other people may prefer their own things, so I don't think we could add anything here.

I just have a little stub that all my functions import:

``` go
// Package logs is a side-effect only package to set up log formatting.
package logs

import (
    "github.com/apex/log"
    "github.com/apex/log/handlers/logfmt"
)

func init() {
    log.SetHandler(logfmt.Default)
}
```

**Comment by dcu** [comment]
ok fair enough. I'm a big fan of structured logging as well :)
