### ISSUE TITLE
CloudWatch Events

### ISSUE THREAD

**Issue by sthulb** [apex/go-apex#18]
Hi, 

I currently have: https://github.com/sthulb/apex-cloudwatch as a separate pkg for handling CloudWatch Events, is this something that could be integrated here?

**Comment by tj** [comment]
Sure! That would be great

**Comment by sthulb** [comment]
Great, I've submitted PR #19

**Comment by rjocoleman** [comment]
Nice PR, I've been using this for about a week and it's been processing Cloudwatch events without issue 👍
