### ISSUE TITLE
Any chance of exposing $context.authorizer.principalId in the Context?

### ISSUE THREAD

**Issue by polds** [apex/go-apex#22]
I see Cognito has recently been added to the Context. Wondering if `$context.authorizer.principalId` could be exposed in the Context as well for those of us implementing custom authorizers.

What's strange is I don't even see it in the `context.ClientContext`. So far the only way I've been able to get it to work is to add it to the Body Request template and read it in the Event.

**Comment by tj** [comment]
I don't use Cognito personally but happy to look at a pull-request!

**Comment by polds** [comment]
Closing this issue. It's an API Gateway thing, not a Lambda thing.
