### ISSUE TITLE
How can I get a environment variable?

### ISSUE THREAD

**Issue by lexrus** [apex/go-apex#35]
I've created a function.json in the same folder of the main.go:
``` json
{
    "environment": {
        "pushMessage": "hello world"
    }
}
```

``` go
func main() {
    apex.HandleFunc(func(event json.RawMessage, ctx *apex.Context) (interface{}, error) {
        // How can I get the pushMessage here?
```

**Comment by mthenw** [comment]
The easiest way is to `Getenv` method from `os` package. 

https://golang.org/pkg/os/#Getenv

**Comment by lexrus** [comment]
Well, that doesn't work.

``` go
log.Print("message: " + os.Getenv("pushMessage"))
```

``` shell
echo '{}' | go run functions/myFunction/main.go
2016/12/12 17:00:08 message: 
```

**Comment by tj** [comment]
@lexrus `echo {} | apex invoke myFunction` will invoke it in AWS, but currently there's no support for executing locally. I usually recommend having libraries and unit tests in place of lots of manual local testing, but if you do `go run` you'll need to `pushMessage=value go run ...` to define the environment variables.

**Comment by lexrus** [comment]
LGTM.
Thank you.
