### ISSUE TITLE
AWS Deprecating NodeJS 0.10?

### ISSUE THREAD

**Issue by steve-gray** [apex/go-apex#36]
Potentially need to bump the shim runtime up to the more modern versions of Node. I've just started getting notifications this week about deprecation of the Lambda Node 0.10 support.

**Comment by tj** [comment]
I think they're getting rid of it mid next year, got some time, but yep definitely need to upgrade

**Comment by ldadams** [comment]
@tj @steve-gray 

How can you get past this error when deploying?

 Error: function ...: InvalidParameterValueException: The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions.
	status code: 400, request id: ...

**Comment by kellyp** [comment]
it looks like it has been fixed (https://github.com/apex/apex/issues/635), just waiting for a release?

**Comment by tj** [comment]
yep
