### ISSUE TITLE
Papertrail: WithField(key, ...) ignored when there's a space in the key

### ISSUE THREAD

**Issue by matthewmueller** [apex/go-apex#45]
Haha, this one was pretty difficult to track down.

```go
log.WithError(errors.New("pq: remaining connection slots are reserved for non-replication superuser connections")).WithField("event ID", 123).Error("unable to connect to postgres")
```

Results in:

```
level=error message="unable to connect to postgres" error="pq: remaining connection slots are reserved for non-replication superuser connections"
```

But

```go
log.WithError(errors.New("pq: remaining connection slots are reserved for non-replication superuser connections")).WithField("eventID", 123).Error("unable to connect to postgres")
```

Works:

```
level=error message="unable to connect to postgres" error="pq: remaining connection slots are reserved for non-replication superuser connections" eventID=123
```

---

Happy to push a fix to this if it's a bug. My guess is that the spaces should be substituted to hyphens, so it's still easily parseable. Alternatively, it may make sense to throw an error if there's a space in the key or document it :-)

**Comment by tj** [comment]
Hmmm documenting is probably best, instead of choosing hyphens or underscores for the user. Since the handler could potentially store in mongo/sql/json etc I'd probably always stick to camelcase or underscore.

**Comment by matthewmueller** [comment]
ah okay, i'll add it in the docs. also my bad, i just realized i opened this in the completely wrong repo!
