### ISSUE TITLE
how to return errorType?

### ISSUE THREAD

**Issue by temoto** [apex/go-apex#46]
Step Functions error catching looks at `errorType` field from Lambda result.

I've tried following code:
```
import apex_fun "github.com/apex/apex/function"
...
// in handler
return nil, &apex_fun.InvokeError{Type: "YandexAccessDenied", Handled: true, Message: "need to update OAuth token"}
```
but for some reason response only contains `errorMessage`, no type.

I could try to return it as successful response. Update: doesn't work.

Looking for suggestion how to implement this properly.

**Comment by tj** [comment]
The sub packages in apex/apex are (implicitly) private, but it seems like what you have should be fine, not sure why it wouldn't be serializing with the type as well

**Comment by temoto** [comment]
Because go-apex `manager.invoke()` takes error string from it.
https://github.com/apex/go-apex/blob/master/apex.go#L145
```
	v, err := m.Handler.Handle(msg.Event, msg.Context)

	if err != nil {
		return &output{Error: err.Error()}
	}
```

**Comment by temoto** [comment]
Following patch seems to fix it.

```diff
type output struct {
---	Error string      `json:"error,omitempty"`
+++	Error error       `json:"error,omitempty"`
	Value interface{} `json:"value,omitempty"`
}
```

Not sure it's backward compatibe yet, so pull request is coming after more testing.

**Comment by temoto** [comment]
Better version here #48 

Sorry I couldn't get around importing apex/function.
On go-apex, callee of handler side, you only need to extract fields like Type, Message, Stack from `output.Error`.
On handler side there must be a conventional API to send those fields to shim.
Putting all this together, I think exporting `apex/function.InvokeError` as public type is simple and clean solution.

**Comment by davidcpell** [comment]
Looks like this issue and the related PR have been around a while! I've been using apex/go for a little while now in vanilla Lambda functions but have run into this problem when trying to use apex/go with Step Functions. The way things are right now, error handling pretty much doesn't work since there needs to be an error type. Seeing that there's this issue, its PR, and #59 for the same problem, is this a "not going to fix"?

**Comment by davidcpell** [comment]
Looks like this might not matter anymore!

<img width="616" alt="screen shot 2018-01-16 at 8 39 29 am" src="https://user-images.githubusercontent.com/1223820/34991770-cd2e40ce-fa98-11e7-8791-796e17930721.png">

**Comment by temoto** [comment]
@davidcpell thanks for notification. Much appreciated.
