### ISSUE TITLE
Cannot find module './index'

### ISSUE THREAD

**Issue by abhisharma** [apex/go-apex#49]
With latest apex/go-apex, I deployed a function written in go lang to AWS and I get following error on invoke:
Cannot find module './index'
Am I missing something?

**Comment by tj** [comment]
Sounds related to https://github.com/apex/apex/issues/700, I haven't had a chance to look into it yet

**Comment by abhisharma** [comment]
Never mind. I reinstalled everything and removed {"runtime":"nodejs4.3"} from project.json and issue got resolved.

**Comment by santhoshdaivajna** [comment]
moved everything from function.json to project.json, removed runtime
```
{
  "name": "func_name",
  "description": "cloudformation custom resource for autoscaling cluster",
  "memory": 128,
  "timeout": 10,
   "role": "rolearn"
}
```
and then ran the deploy again

```
apex deploy asg --log-level debug > out.zip
   • loading functions in functions
   • open                      env= function=asg
   • inferring runtime         env= function=asg
   • inferred runtime          env= function=asg runtime=golang
   • deploying 1 functions
   • deploying                 env= function=asg
   • creating build            env= function=asg
   • hook                      command=GOOS=linux GOARCH=amd64 go build -o main *.go env= function=asg hook=build
   ⨯ Error: function asg: build hook:
```

**Comment by santhoshdaivajna** [comment]
After removing runtime from project.json

`apex build asg > out.zip     `   
created a zip file with index.js
`apex deploy asg > out.zip`
did not include the index.js in zip file

**Comment by tj** [comment]
@santhoshdaivajna `deploy` doesn't output a zip
