### ISSUE TITLE
Fix proxy binary support

### ISSUE THREAD

**Issue by tj** [apex/go-apex#51]
Seems to respond with base64, APIG should be decoding it when the flag is set.

**Comment by kothar** [comment]
You need to enable binary support in APIG in order for the Base64 flag to be respected. I tried various non-base64 encoded output with just escaped strings, but it didn't seem to work (jpegs for example), presumably due to the API gateway response transformation trying to parse it.

**Comment by tj** [comment]
Oh wtf, that's weird.. seems like something you shouldn't have to manually enable
