### ISSUE TITLE
Poor cold start performance 

### ISSUE THREAD

**Issue by heri16** [apex/go-apex#53]
Nodejs runtime has poor cold start performance according to the benchmarks at https://github.com/eawsy/aws-lambda-go-shim

Should we consider switching to python?

**Comment by tj** [comment]
Ah follow this one for that https://github.com/apex/apex/issues/704. Ideally we can support both techniques with the same API, but it'll be a while until I have to get to that. For sustained usage it's not very relevant, but I do have some future use-cases in mind that I think will apply, so I might end up writing it.
