### ISSUE TITLE
Automating deployment via Travis CI

### ISSUE THREAD

**Issue by l0010o0001l** [apex/go-apex#57]
Hallo there -- 

I've been trying to find a solution for automating the deployment of Go Lambdas that use `go-apex` in Travis CI. The gist is that Apex is installed, then when on a specific branch, run the `apex deploy` command for each Lambda in a directory. For Go Lambdas only I am returned errors like the following: 

```
Deploying dependencies to testing
   ⨯ Error: function remote: build hook: main.go:15:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/home/travis/.gimme/versions/go1.4.1.linux.amd64/src/github.com/Sirupsen/logrus (from $GOROOT)
	($GOPATH not set)
```

Deploying Go Lambdas works locally, however Travis CI builds do not recognize the dependencies inside of the Go Lambda. I am very new to `Go`. Any help regarding this issue is wonderfully appreciated. Thank you!

**Comment by tj** [comment]
@l0010o0001l hey! You'll probably have to configure Travis to run `go get ./...` in your dir to grab the deps, or alternatively use Go's newer vendoring support which stores the deps in ./vendor

**Comment by l0010o0001l** [comment]
Thanks @tj! 

For those wondering, [Glide](https://github.com/Masterminds/glide) is a good resource for implementing Go's newer vendoring support.
