### ISSUE TITLE
Binary Support

### ISSUE THREAD

**Issue by simpleblack** [apex/go-apex#58]
Hi.
go-apex binary not support?
go-apex  = response only `(interface{}, error)`

how can response binary?

I want this implemented
https://aws.amazon.com/ko/blogs/compute/binary-support-for-api-integrations-with-amazon-api-gateway/

**Comment by tj** [comment]
Ahh the binary has to be base64 encoded, go-apex has proxy support as well which does this https://github.com/apex/go-apex/tree/master/proxy

**Comment by simpleblack** [comment]
I want easily use binary not used proxy.
`apex.HandleFunc(func() (string, error)` = text
`apex.HandleFunc(func() (string, error)` = binary(api gateway Base64Encoded true)
`apex.HandleFunc(func() (interface{}, error)` = json

Is it impossible?
Why used proxy?

Thank you.

**Comment by tj** [comment]
Lambda only supports JSON output, so binary has to be base64 encoded at the moment

**Comment by simpleblack** [comment]
Thank you
