### ISSUE TITLE
 [shim] unexpected line - do not use stdout

### ISSUE THREAD

**Issue by xoraes** [apex/go-apex#61]
I am seeing this on cloudwatch logs: 

[shim] unexpected line - do not use stdout: `{"value":{"blah":"blah"}}`

My logger outputs are fine as they are all writing to stderr. Is shim causing issues?

**Comment by tj** [comment]
Are you sure you're using stderr? see https://github.com/apex/apex/blob/master/shim/index.js#L59

**Comment by xoraes** [comment]
I have this in some places
`var logctx = logging.Logctx
logctx.Trace("xx")
`

**Comment by xoraes** [comment]
`package logging

import (
	"github.com/apex/log"
	logjson "github.com/apex/log/handlers/json"
	"os"
)

var Logctx *log.Entry

func init() {
	log.SetHandler(logjson.New(os.Stderr)) // this is done because apex wants us to write to stderr
	log.SetLevel(log.DebugLevel)
	Logctx = log.WithFields(log.Fields{
		"application": "go-lambda-cms",
		"environment": os.Getenv("ENVIRONMENT"),
	})
}
`

**Comment by xoraes** [comment]
also I haven't changed any of my code in a long time, but I redeployed some functions recently which probably trigger this: curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh \

**Comment by tj** [comment]
hmm strange I'll see if I can reproduce

**Comment by xoraes** [comment]
thanks @tj let me know if i can help in any way

**Comment by xoraes** [comment]
+ @skabbes ^^

**Comment by xoraes** [comment]
@tj any luck reproducing this?

**Comment by xoraes** [comment]
this happened because go-apex was upgraded but apex wasn't. :(

**Comment by tj** [comment]
ohh shit :( hmm tricky with the current state of dep management

**Comment by bearmini** [comment]
The same issue happened to me. In my case, apex was the latest, but go-apex was not.
`go get -u github.com/apex/go-apex` fixed the issue.
