### ISSUE TITLE
remove node shim as aws now supports golang natively

### ISSUE THREAD

**Issue by xoraes** [apex/go-apex#67]

**Comment by davidcpell** [comment]
Go support has been announced but not launched.

**Comment by n2p5** [comment]
this is promising. https://aws.amazon.com/blogs/compute/announcing-go-support-for-aws-lambda/

**Comment by tj** [comment]
On it :D will likely have this in tomorrow

**Comment by ravern** [comment]
This will change the API for the Lambda contexts (i.e. *apex.Context) right? I'm assuming the API will switch to using the official repo for this.

The repository:
https://github.com/aws/aws-lambda-go

**Comment by vishal8492** [comment]
@ravernkoh I'd assume so, I was using apex proxy for api gateway invocations. I might need to rewrite and delegate by manually doing pattern matching now  :)

**Comment by tj** [comment]
@ravernkoh yep :D

Closing since it's in apex/apex now. This repo is basically irrelevant now unless you're using the older versions of apex.
