### ISSUE TITLE
Example of importing third party packages?

### ISSUE THREAD

**Issue by lox** [apex/go-apex#8]
I'm sure there is an obvious answer but what's the best way to import third party packages or subpackages of ones own projects?

**Comment by tj** [comment]
For which lang? Or do you mean entire Apex projects?

**Comment by lox** [comment]
I think I figured out my own question, my go-apex project wasn't in my build path. If it had been I could have used a full import for a sub package (function of `test`, with a subfolder/package of `subfolder`). As it stands, I simply used a relative import for `./subfolder`, which isn't great go, but works.

**Comment by tj** [comment]
ahh hmm I've been just using regular GOPATH for my project, nothing relative
